server:
  port: 8080
spring:
  application:
    name: gretting_service
management:
  endpoints:
    web:
      exposure:
        include:
          - "*"
          
  endpoint:
    health:
      show-details: ALWAYS
greeting-service:
  greeting: "Hello"
  default-value: "Worlds"